-- liquibase formatted sql

-- changeset tim0shkaa:notification-1
CREATE TABLE notification_log
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_type    VARCHAR(50)              NOT NULL,
    guest_id      BIGINT                   NOT NULL,
    booking_id    BIGINT                   NOT NULL,
    status        VARCHAR(50)              NOT NULL,
    payload       TEXT                     NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    retry_count   INTEGER                  NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notification_log PRIMARY KEY (id)
);

-- changeset tim0shkaa:notification-2
CREATE TABLE processed_events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     VARCHAR(255)             NOT NULL,
    processed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (id)
);

-- changeset tim0shkaa:notification-3
ALTER TABLE processed_events
    ADD CONSTRAINT uc_processed_events_event_id UNIQUE (event_id);