-- liquibase formatted sql

-- changeset tim0shkaa:payment-1
CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id BIGINT NOT NULL,
    guest_id BIGINT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(50) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    provider_payment_id VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

-- changeset tim0shkaa:payment-2
CREATE TABLE payment_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    error_code VARCHAR(255),
    error_message VARCHAR(255),
    attempted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_payment_attempt PRIMARY KEY (id)
);

-- changeset tim0shkaa:payment-3
CREATE TABLE refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id BIGINT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    processed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refund PRIMARY KEY (id)
);

-- changeset tim0shkaa:payment-4
ALTER TABLE payment_attempt ADD CONSTRAINT fk_payment_attempt_on_payment FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE;

-- changeset tim0shkaa:payment-5
ALTER TABLE refund ADD CONSTRAINT fk_refund_on_payment FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE;

-- changeset tim0shkaa:payment-6
CREATE INDEX idx_payment_booking_id ON payment (booking_id);

-- changeset tim0shkaa:payment-7
CREATE INDEX idx_payment_guest_id ON payment (guest_id);

-- changeset tim0shkaa:payment-8
CREATE INDEX idx_payment_attempt_payment_id ON payment_attempt (payment_id);

-- changeset tim0shkaa:payment-9
CREATE INDEX idx_refund_payment_id ON refund (payment_id);