-- liquibase formatted sql

-- changeset tim0shkaa:payment-10
CREATE TABLE processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (id)
);

-- changeset tim0shkaa:payment-11
ALTER TABLE processed_events ADD CONSTRAINT uc_processed_events_event_id UNIQUE (event_id);