-- liquibase formatted sql

-- changeset tim0shkaa:booking-16
ALTER TABLE booking ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now();

-- changeset tim0shkaa:booking-17
CREATE TABLE processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    processed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (id)
);

-- changeset tim0shkaa:booking-18
ALTER TABLE processed_events ADD CONSTRAINT uc_processed_events_event_id UNIQUE (event_id);