-- liquibase formatted sql

-- changeset tim0shkaa:review-1
CREATE TABLE review
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id          BIGINT                      NOT NULL,
    guest_id            BIGINT                      NOT NULL,
    hotel_id            BIGINT                      NOT NULL,
    room_type_id        BIGINT                      NOT NULL,
    overall_rating      INTEGER                     NOT NULL,
    cleanliness_rating  INTEGER                     NOT NULL,
    service_rating      INTEGER                     NOT NULL,
    location_rating     INTEGER                     NOT NULL,
    value_rating        INTEGER                     NOT NULL,
    title               VARCHAR(255)                NOT NULL,
    body                TEXT                        NOT NULL,
    is_verified         BOOLEAN                     NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

-- changeset tim0shkaa:review-2
CREATE TABLE review_reply
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    review_id   BIGINT                      NOT NULL,
    author_id   BIGINT                      NOT NULL,
    body        TEXT                        NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_review_reply PRIMARY KEY (id)
);

-- changeset tim0shkaa:review-3
CREATE TABLE rating_aggregate
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    target_type          VARCHAR(50)                 NOT NULL,
    target_id            BIGINT                      NOT NULL,
    avg_rating           NUMERIC(3, 2)               NOT NULL,
    total_reviews        INTEGER                     NOT NULL,
    rating_distribution  JSONB,
    CONSTRAINT pk_rating_aggregate PRIMARY KEY (id)
);

-- changeset tim0shkaa:review-4
CREATE TABLE eligible_booking
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id   BIGINT                      NOT NULL,
    guest_id     BIGINT                      NOT NULL,
    hotel_id     BIGINT                      NOT NULL,
    room_type_id BIGINT                      NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_eligible_booking PRIMARY KEY (id)
);

-- changeset tim0shkaa:review-5
CREATE TABLE processed_events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     VARCHAR(255)                NOT NULL,
    processed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (id)
);

-- changeset tim0shkaa:review-6
ALTER TABLE review_reply
    ADD CONSTRAINT fk_review_reply_on_review FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE;

-- changeset tim0shkaa:review-7
ALTER TABLE eligible_booking
    ADD CONSTRAINT uc_eligible_booking_booking_id UNIQUE (booking_id);

-- changeset tim0shkaa:review-8
ALTER TABLE review
    ADD CONSTRAINT uc_review_booking_id UNIQUE (booking_id);

-- changeset tim0shkaa:review-9
ALTER TABLE processed_events
    ADD CONSTRAINT uc_processed_events_event_id UNIQUE (event_id);

-- changeset tim0shkaa:review-10
CREATE INDEX idx_review_hotel_id ON review (hotel_id);

-- changeset tim0shkaa:review-11
CREATE INDEX idx_review_guest_id ON review (guest_id);

-- changeset tim0shkaa:review-12
CREATE INDEX idx_rating_aggregate_target ON rating_aggregate (target_type, target_id);